-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Juniper.InputObject
import Juniper.Interface
import Juniper.Object
import Juniper.Scalar
import Juniper.ScalarCodecs
import Juniper.Union


type alias CreateItemRequiredArguments =
    { title : String }


createItem :
    CreateItemRequiredArguments
    -> SelectionSet decodesTo Juniper.Object.Item
    -> SelectionSet decodesTo RootMutation
createItem requiredArgs____ object____ =
    Object.selectionForCompositeField "createItem" [ Argument.required "title" requiredArgs____.title Encode.string ] object____ Basics.identity


type alias UpdateItemRequiredArguments =
    { id : String
    , input : Juniper.InputObject.ItemInput
    }


updateItem :
    UpdateItemRequiredArguments
    -> SelectionSet decodesTo Juniper.Object.Item
    -> SelectionSet decodesTo RootMutation
updateItem requiredArgs____ object____ =
    Object.selectionForCompositeField "updateItem" [ Argument.required "id" requiredArgs____.id Encode.string, Argument.required "input" requiredArgs____.input Juniper.InputObject.encodeItemInput ] object____ Basics.identity
